import { textToSpeech, speechToText, voiceSpeaker, voiceEncoding, voiceContentType } from "./voice";
import { withSecurityHeaders, clientIp, rateLimit, isAdminRequest } from "./security";
import { recordTraffic, queryTraffic, hashIp } from "./analytics";

export interface Env {
  AI: Ai; ASSETS: Fetcher; GROQ_API_KEY?: string; GOOGLE_API_KEY?: string; NVIDIA_API_KEY?: string; HF_TOKEN?: string;
  ELEVENLABS_API_KEY?: string; ELEVENLABS_VOICE_ID?: string; ELEVENLABS_MODEL?: string; GROQ_MODEL?: string; GOOGLE_MODEL?: string;
  NVIDIA_MODEL?: string; MEDICAL_MODEL?: string; ADMIN_TOKEN?: string; NEXA_ANALYTICS?: { writeDataPoint: (point: { blobs?: string[]; doubles?: number[] }) => void };
  CF_ACCOUNT_ID?: string; CF_ANALYTICS_TOKEN?: string;
}
type Message = { role: "system" | "user" | "assistant"; content: string };
type ProviderResult = { content: string; provider: string; model: string };
const BRAND="Nexa AI", POWERED_BY="SPRINGNEXA PRIVATE LIMITED (IT Division)", COMPANY="SpringNexa Private Limited";
const DEFAULT_SYSTEM=`You are Nexa AI, powered by SPRINGNEXA PRIVATE LIMITED (IT Division). Be accurate, useful and concise. Never claim to be a doctor.`;
const MEDICAL_SYSTEM=`You are Nexa AI Medical, powered by SPRINGNEXA PRIVATE LIMITED (IT Division). Provide medical education and decision support, not a definitive diagnosis or prescription. Clearly distinguish possibilities from diagnosis. For emergencies advise immediate local medical care. Respond in the user's requested language when specified.`;
const TIMEOUT_MS=12000;
const GROQ_FREE=["openai/gpt-oss-120b","openai/gpt-oss-20b","openai/gpt-oss-safeguard-20b","qwen/qwen3.6-27b","qwen/qwen3.8-27b","groq/compound-mini"];
const CLOUDFLARE_FREE=["@cf/nvidia/nemotron-3-120b-a12b","@cf/zai-org/glm-4.7-flash","@cf/google/gemma-4-26b-a4b-it","@cf/meta/llama-4-scout-17b-16e-instruct"];
const GOOGLE_FREE=["gemini-3.1-flash-lite-preview","gemini-2.5-flash","gemini-2.5-flash-lite"];
const MEDICAL_DEFAULT="google/medgemma-27b-it";
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function getMessages(body:any):Message[]{const m=Array.isArray(body?.messages)?body.messages:[];return m.filter((x:any)=>x&&["system","user","assistant"].includes(x.role)&&typeof x.content==="string").slice(-30)}
async function fetchTimeout(url:string,init:RequestInit){return fetch(url,{...init,signal:AbortSignal.timeout(TIMEOUT_MS)})}
async function openAI(apiKey:string,url:string,model:string,msgs:Message[],provider:string):Promise<ProviderResult>{const r=await fetchTimeout(url,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${apiKey}`},body:JSON.stringify({model,messages:msgs,temperature:.2,max_tokens:1024,stream:false})});if(!r.ok)throw new Error(`${provider}:${r.status}`);const d:any=await r.json();const c=d?.choices?.[0]?.message?.content;if(typeof c!=="string"||!c.trim())throw new Error(`${provider}:invalid_response`);return{content:c,provider,model}}
async function cloudflare(env:Env,msgs:Message[],model:string):Promise<ProviderResult>{const d:any=await env.AI.run(model,{messages:msgs,max_tokens:1024,temperature:.2});const c=d?.response??d?.choices?.[0]?.message?.content;if(typeof c!=="string"||!c.trim())throw new Error("cloudflare:invalid_response");return{content:c,provider:"cloudflare",model}}
async function google(env:Env,msgs:Message[],model:string):Promise<ProviderResult>{if(!env.GOOGLE_API_KEY)throw new Error("google:not_configured");const system=msgs.find(m=>m.role==="system")?.content;const contents=msgs.filter(m=>m.role!=="system").map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}));const r=await fetchTimeout(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(env.GOOGLE_API_KEY)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...system?{systemInstruction:{parts:[{text:system}]}}:{},contents,generationConfig:{temperature:.2,maxOutputTokens:1024}})});if(!r.ok)throw new Error(`google:${r.status}`);const d:any=await r.json();const c=d?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||"").join("");if(!c)throw new Error("google:invalid_response");return{content:c,provider:"google",model}}
async function medical(env:Env,msgs:Message[],model:string):Promise<ProviderResult>{if(!env.HF_TOKEN)throw new Error("medical:not_configured");return openAI(env.HF_TOKEN,"https://router.huggingface.co/v1/chat/completions",model,msgs,"medical")}
async function answer(env:Env,msgs:Message[],provider?:string,requestedModel?:string):Promise<ProviderResult>{const errors:string[]=[];const selected=(provider||"auto").toLowerCase();const order=selected==="auto"?["cloudflare","groq","google","nvidia"]:[selected];for(const p of order){try{if(p==="medical"){try{return await medical(env,msgs,requestedModel||env.MEDICAL_MODEL||MEDICAL_DEFAULT)}catch(e){errors.push(e instanceof Error?e.message:"medical:error");}}else if(p==="cloudflare"){for(const model of requestedModel?.startsWith("@cf/")?[requestedModel]:CLOUDFLARE_FREE){try{return await cloudflare(env,msgs,model)}catch(e){errors.push(e instanceof Error?e.message:`cloudflare:${model}:error`)}}}else if(p==="groq"&&env.GROQ_API_KEY){for(const model of env.GROQ_MODEL?[env.GROQ_MODEL]:GROQ_FREE){try{return await openAI(env.GROQ_API_KEY,"https://api.groq.com/openai/v1/chat/completions",model,msgs,"groq")}catch(e){errors.push(e instanceof Error?e.message:`groq:${model}:error`)}}}else if(p==="google"&&env.GOOGLE_API_KEY){for(const model of env.GOOGLE_MODEL?[env.GOOGLE_MODEL]:GOOGLE_FREE){try{return await google(env,msgs,model)}catch(e){errors.push(e instanceof Error?e.message:`google:${model}:error`)}}}else if(p==="nvidia"&&env.NVIDIA_API_KEY){try{return await openAI(env.NVIDIA_API_KEY,"https://integrate.api.nvidia.com/v1/chat/completions",env.NVIDIA_MODEL||"nvidia/nemotron-3.5-lightning-30b-a3b",msgs,"nvidia")}catch(e){errors.push(e instanceof Error?e.message:"nvidia:error")}}else errors.push(`${p}:not_configured`)}catch(e){errors.push(e instanceof Error?e.message:`${p}:error`)}}throw new Error(errors.join(","))}
function cors(r:Response){const h=new Headers(r.headers);h.set("access-control-allow-origin","*");h.set("access-control-allow-methods","GET,POST,OPTIONS");h.set("access-control-allow-headers","content-type,authorization");return withSecurityHeaders(new Response(r.body,{status:r.status,statusText:r.statusText,headers:h}))}
function livePage(asset:Response){return new HTMLRewriter().on("body",{element(e){e.append(`<script>(()=>{const beat=()=>{try{navigator.sendBeacon('/v1/telemetry',new Blob([JSON.stringify({event:'heartbeat',path:location.pathname})],{type:'application/json'}))}catch{fetch('/v1/telemetry',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event:'heartbeat',path:location.pathname}),keepalive:true}).catch(()=>{})}};beat();setInterval(beat,20000)})()</script>`,{html:true})}}).transform(asset)}
export default {async fetch(request:Request,env:Env):Promise<Response>{
  if(request.method==="OPTIONS")return cors(new Response(null,{status:204}));const url=new URL(request.url),ip=clientIp(request),isApi=url.pathname.startsWith("/v1/")||url.pathname==="/health";
  if(isApi&&!rateLimit(`${ip}:${url.pathname}`,url.pathname.startsWith("/v1/audio/")?20:60))return cors(json({error:"Too many requests"},429));
  if(url.pathname==="/health"&&request.method==="GET")return cors(json({ok:true,service:BRAND,poweredBy:POWERED_BY,company:COMPANY,division:"IT Division",modes:["auto","medical","voice"]}));
  if(url.pathname==="/v1/telemetry"&&request.method==="POST"){try{const b:any=await request.json();const event=typeof b?.event==="string"?b.event.slice(0,32):"pageview";const path=typeof b?.path==="string"?b.path.slice(0,120):"/";const country=request.headers.get("CF-IPCountry")||"unknown";recordTraffic(env,event,path,await hashIp(ip),country);return cors(json({ok:true}))}catch{return cors(json({ok:false},202))}}
  if(url.pathname==="/v1/admin/status"&&request.method==="GET"){if(!isAdminRequest(request,env.ADMIN_TOKEN))return cors(json({error:"Unauthorized"},401));return cors(json({ok:true,admin:true,service:BRAND,security:"hardened-baseline",secretsConfigured:{groq:!!env.GROQ_API_KEY,google:!!env.GOOGLE_API_KEY,nvidia:!!env.NVIDIA_API_KEY,medical:!!env.HF_TOKEN,elevenlabs:!!env.ELEVENLABS_API_KEY,admin:!!env.ADMIN_TOKEN},analyticsConfigured:!!(env.NEXA_ANALYTICS&&env.CF_ACCOUNT_ID&&env.CF_ANALYTICS_TOKEN)}))}
  if(url.pathname==="/v1/admin/traffic"&&request.method==="GET"){if(!isAdminRequest(request,env.ADMIN_TOKEN))return cors(json({error:"Unauthorized"},401));try{const q=await queryTraffic(env,"SELECT count() AS requests, count(DISTINCT blob3) AS users FROM nexa_ai_traffic WHERE timestamp > NOW() - INTERVAL '5' MINUTE");const h=await queryTraffic(env,"SELECT count() AS requests FROM nexa_ai_traffic WHERE timestamp > NOW() - INTERVAL '1' HOUR");return cors(json({ok:true,window:"5m",liveUsers:Number((q as any)?.data?.[0]?.users||0),requests5m:Number((q as any)?.data?.[0]?.requests||0),requests1h:Number((h as any)?.data?.[0]?.requests||0),updatedAt:new Date().toISOString()}))}catch(e){return cors(json({ok:false,configured:false,error:e instanceof Error?e.message:"analytics_error"},503))}}
  if(url.pathname==="/v1/voice/capabilities"&&request.method==="GET")return cors(json({brand:BRAND,product:"Nexa Voice",speechToText:true,textToSpeech:true,providers:{elevenlabs:!!env.ELEVENLABS_API_KEY,cloudflare:true},languages:["en","hi","ur","doi","ks","goj"],formats:["mp3","opus","wav"]}));
  if(url.pathname==="/v1/audio/speech"&&request.method==="POST"){try{const b:any=await request.json(),text=typeof b?.input==="string"?b.input:typeof b?.text==="string"?b.text:"";if(!text.trim())return cors(json({error:"input is required"},400));const enc=voiceEncoding(b?.response_format||b?.format),a=await textToSpeech(env,text,voiceSpeaker(b?.voice),enc);return cors(new Response(a.body,{status:a.status,headers:{"content-type":voiceContentType(enc),"cache-control":"no-store","x-nexa-product":"Nexa Voice"}}))}catch{return cors(json({error:"Voice generation failed"},503))}}
  if(url.pathname==="/v1/audio/transcriptions"&&request.method==="POST"){try{const ct=request.headers.get("content-type")||"";let audio:ArrayBuffer,language:string|undefined;if(ct.includes("multipart/form-data")){const f=await request.formData(),file=f.get("file");if(!(file instanceof File))return cors(json({error:"audio file is required"},400));audio=await file.arrayBuffer();language=typeof f.get("language")==="string"?String(f.get("language")):undefined}else{audio=await request.arrayBuffer();language=url.searchParams.get("language")||undefined}const r=await speechToText(env,audio,language);return cors(json({brand:BRAND,product:"Nexa Voice",text:r.text,wordCount:r.wordCount,vtt:r.vtt}))}catch{return cors(json({error:"Voice transcription failed"},503))}}
  if(url.pathname==="/v1/models"&&request.method==="GET")return cors(json({brand:BRAND,poweredBy:POWERED_BY,company:COMPANY,models:[{id:"auto",name:"Nexa AI Auto",type:"general"},{id:"medical",name:"Nexa AI Medical",type:"medical"},{id:"voice",name:"Nexa Voice",type:"voice"}]}));
  if(url.pathname==="/v1/chat/completions"&&request.method==="POST"){try{const b:any=await request.json(),selected=typeof b.provider==="string"?b.provider:typeof b.mode==="string"?b.mode:"auto",msgs=getMessages(b);if(!msgs.some(m=>m.role==="user"))return cors(json({error:"messages with a user message are required"},400));const medicalMode=selected.toLowerCase()==="medical";if(!msgs.some(m=>m.role==="system")){const lang=typeof b.language==="string"?b.language:"";msgs.unshift({role:"system",content:(medicalMode?MEDICAL_SYSTEM:DEFAULT_SYSTEM)+(lang?` Preferred response language: ${lang}.`:"")})}const result=await answer(env,msgs,selected,typeof b.model==="string"?b.model:undefined);return cors(json({id:crypto.randomUUID(),object:"chat.completion",created:Math.floor(Date.now()/1000),brand:BRAND,poweredBy:POWERED_BY,company:COMPANY,provider:result.provider,model:result.model,choices:[{index:0,message:{role:"assistant",content:result.content},finish_reason:"stop"}]}))}catch(e){return cors(json({error:"AI service temporarily unavailable",detail:e instanceof Error?e.message:"provider_error"},503))}}
  const asset=await env.ASSETS.fetch(request);return withSecurityHeaders(url.pathname==="/"&&request.method==="GET"?livePage(asset):asset);
}};
